use super::entities::Entity;
use super::rooms::Room;
use super::vocab::{Action, Motion, Word};
use phf::{Map, phf_map};
use unicase::UniCase;

pub(crate) static VOCABULARY: Map<UniCase<&'static str>, Word> = phf_map! {
    UniCase::ascii("N") => Word::Motion(Motion::North),
    UniCase::ascii("NORTH") => Word::Motion(Motion::North),
    UniCase::ascii("S") => Word::Motion(Motion::South),
    UniCase::ascii("SOUTH") => Word::Motion(Motion::South),
    UniCase::ascii("E") => Word::Motion(Motion::East),
    UniCase::ascii("EAST") => Word::Motion(Motion::East),
    UniCase::ascii("W") => Word::Motion(Motion::West),
    UniCase::ascii("WEST") => Word::Motion(Motion::West),
    UniCase::ascii("EXAMINE") => Word::Action(Action::Examine),
    UniCase::ascii("DESCRIBE") => Word::Action(Action::Examine),
    UniCase::ascii("LOOK") => Word::Look,
    UniCase::ascii("AT") => Word::At,
    UniCase::ascii("@") => Word::At,
    UniCase::ascii("ROOM") => Word::Room,
    UniCase::ascii("READ") => Word::Action(Action::Read),
    UniCase::ascii("BACK") => Word::Action(Action::Back),
    UniCase::ascii("RETURN") => Word::Action(Action::Back),
    UniCase::ascii("RETREAT") => Word::Action(Action::Back),
    UniCase::ascii("QUIT") => Word::Action(Action::Quit),
    UniCase::ascii("EXIT") => Word::Action(Action::Quit),
    UniCase::ascii("BANQUET") => Word::Entity(Entity::Banquet),
    UniCase::ascii("FOOD") => Word::Entity(Entity::Banquet),
    UniCase::ascii("DINNER") => Word::Entity(Entity::Banquet),
    UniCase::ascii("BOOKS") => Word::Entity(Entity::Books),
    UniCase::ascii("BOOK") => Word::Entity(Entity::Books),
    UniCase::ascii("CHAIRS") => Word::Entity(Entity::Cushions),
    UniCase::ascii("CHAIR") => Word::Entity(Entity::Cushions),
    UniCase::ascii("CUSHIONS") => Word::Entity(Entity::Cushions),
    UniCase::ascii("CUSHION") => Word::Entity(Entity::Cushions),
    UniCase::ascii("PILLOWS") => Word::Entity(Entity::Cushions),
    UniCase::ascii("PILLOW") => Word::Entity(Entity::Cushions),
    UniCase::ascii("GLOBE") => Word::Entity(Entity::Globe),
    UniCase::ascii("MURAL") => Word::Entity(Entity::Mural),
    UniCase::ascii("SUN") => Word::Entity(Entity::Mural),
    UniCase::ascii("PAINTING") => Word::Entity(Entity::Painting),
    UniCase::ascii("MOON") => Word::Entity(Entity::Painting),
    UniCase::ascii("EASEL") => Word::Entity(Entity::Painting),
    UniCase::ascii("PHOTO") => Word::Entity(Entity::PenguinPhoto),
    UniCase::ascii("PHOTOGRAPH") => Word::Entity(Entity::PenguinPhoto),
    UniCase::ascii("PENGUINS") => Word::Entity(Entity::PenguinPhoto),
    UniCase::ascii("PLANS") => Word::Entity(Entity::SecretPlans),
    UniCase::ascii("TIC-TAC-TOE") => Word::Entity(Entity::TicTacToe),
    UniCase::ascii("TIC-TACK-TOE") => Word::Entity(Entity::TicTacToe),
    UniCase::ascii("GRID") => Word::Entity(Entity::TicTacToe),
    UniCase::ascii("FLOOR") => Word::Entity(Entity::TicTacToe),
};

pub(crate) const TRAVEL_TABLE: [((Room, Motion), Room); 24] = [
    ((Room::NorthWest, Motion::East), Room::North),
    ((Room::NorthWest, Motion::South), Room::West),
    ((Room::North, Motion::West), Room::NorthWest),
    ((Room::North, Motion::South), Room::Center),
    ((Room::North, Motion::East), Room::NorthEast),
    ((Room::NorthEast, Motion::West), Room::North),
    ((Room::NorthEast, Motion::South), Room::East),
    ((Room::West, Motion::North), Room::NorthWest),
    ((Room::West, Motion::East), Room::Center),
    ((Room::West, Motion::South), Room::SouthWest),
    ((Room::Center, Motion::North), Room::North),
    ((Room::Center, Motion::East), Room::East),
    ((Room::Center, Motion::West), Room::West),
    ((Room::Center, Motion::South), Room::South),
    ((Room::East, Motion::North), Room::NorthEast),
    ((Room::East, Motion::West), Room::Center),
    ((Room::East, Motion::South), Room::SouthEast),
    ((Room::SouthWest, Motion::East), Room::South),
    ((Room::SouthWest, Motion::North), Room::West),
    ((Room::South, Motion::West), Room::SouthWest),
    ((Room::South, Motion::North), Room::Center),
    ((Room::South, Motion::East), Room::SouthEast),
    ((Room::SouthEast, Motion::West), Room::South),
    ((Room::SouthEast, Motion::North), Room::East),
];

pub(crate) const FIXED_ENTITIES: [(Entity, Room); 9] = [
    (Entity::Banquet, Room::NorthWest),
    (Entity::Books, Room::SouthWest),
    (Entity::Cushions, Room::NorthEast),
    (Entity::Globe, Room::North),
    (Entity::Mural, Room::East),
    (Entity::Painting, Room::West),
    (Entity::PenguinPhoto, Room::South),
    (Entity::SecretPlans, Room::SouthEast),
    (Entity::TicTacToe, Room::Center),
];
