[package]
name = "advcore"
edition.workspace = true
rust-version.workspace = true
#description = ???
authors.workspace = true
#repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
